set(HORSE_SOURCES
    src/lib/action.c
    src/lib/action_list.c
    src/lib/action_set.c
    src/lib/flow.c
    src/lib/heap.c
    src/lib/instruction.c
    src/lib/instruction_set.c
    src/lib/json_topology.c
    src/lib/net_utils.c
    src/lib/netflow.c
    src/lib/of_pack.c
    src/lib/of_unpack.c
    src/lib/signal_handler.c
    src/lib/sim_event.c
    src/lib/timer.c
    src/lib/util.c
    src/net/app/app.c
    src/net/app/ping.c
    src/net/app/raw_udp.c
    src/net/arp_table.c
    src/net/buffer_state.c
    src/net/datapath.c
    src/net/dp_actions.c
    src/net/dp_control.c
    src/net/flow_table.c
    src/net/host.c
    src/net/legacy_node.c
    src/net/live_flow.c
    src/net/node.c
    src/net/port.c
    src/net/route_table.c
    src/net/router.c
    src/net/routing/exabgp_daemon.c
    src/net/routing/quagga_daemon.c
    src/net/topology.c
    src/routing_msg/routing_msg.c
    src/sim/conn_manager.c
    src/sim/event_handler.c
    src/sim/scheduler.c
    src/sim/server.c
    src/sim/setup.c
    src/sim/sim.c
    src/sim/sim_config.c)
